# Generated by Django 4.0.1 on 2022-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_payment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='user', max_length=100)),
                ('password', models.CharField(default='123456', max_length=100)),
            ],
        ),
    ]
